apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java-deployment
  labels:
    app: hello-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: hello-world-java
        image: docker.local:5000/beer/helloworld:latest
        ports:
        - containerPort: 3000